# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: '2'

volumes:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
      
  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb:/opt/data
    command: --init-file /opt/data/migration.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ibanez
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    restart: unless-stopped
    ports:
        - 8181:80
    links:
        - mariadb:mariadb
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: mysql