version: '2'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    volumes_from:
      - php

  php:
    build: ./docker/php/
    expose:
      - "9000"
    working_dir: /www
    restart: always
    volumes:
      - ./www/:/var/www/html

  database:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb/dev57.sql:/docker-entrypoint-initdb.d/dev57.sql
    environment:
      - "MYSQL_DATABASE=ibanez"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - 3307:3306

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    restart: unless-stopped
    ports:
        - 8181:80
    links:
        - database:mysql
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: mysql
